name: Deploy landing page

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Run custom action
          uses: ./.github/actions/React-Eximon@master # Replace with the correct owner/repo@ref